### ISSUE TITLE
Need add batching config

### ISSUE THREAD

**Issue by Aquamars** [iKala/Samsara#1]
**Add batching config**

https://github.com/iKala/Samsara/blob/master/src/job.js#L31
```javascript
 const { topicSuffix } = this.config; 
=> const { topicSuffix, batchingConfig = {} } = this.config;
```

https://github.com/iKala/Samsara/blob/master/src/job.js#L44
```javascript
return topic.publisher().publish(dataBuffer, this.data);
=> return topic.publisher(batchingConfig).publish(dataBuffer, this.data);
```

The `batchingConfig` should be:
```javascript
{
  batching: {
    maxMessages: 10,
    maxMilliseconds: 10000,
  },
}
```

**Comment by Calvin-Huang** [comment]
Hi @Aquamars ,

Thanks for your contribution. Can you provide the doc reference for adding batching config to the publisher? I couldn't find the config sample at google pubsub repo 🤔.

In the other hand, I guess there must be other configs for publisher or subscriber, it might be better to give the omni-option for them not only `batchingOption`.

**Comment by Aquamars** [comment]
Hi~ @Calvin-Huang ,
Here are reference: 
On the answer: https://stackoverflow.com/questions/49070836/batching-pubsub-requests

In google pubsub repo, batching config on `topic()`: 
https://github.com/googleapis/nodejs-pubsub/blob/master/samples/topics.js#L161
https://cloud.google.com/pubsub/docs/publisher#batching
