### ISSUE TITLE
Missing a method or parameter to do message.nack()

### ISSUE THREAD

**Issue by Aquamars** [iKala/Samsara#6]
Only do `message.ack()`.
https://github.com/iKala/Samsara/blob/master/src/worker.js#L58

Sometime doesn't need ack the message.

`message.nack()` of ref:
https://github.com/googleapis/nodejs-pubsub/blob/master/src/subscription.ts#L191
https://cloud.google.com/nodejs/docs/reference/pubsub/0.19.x/Subscription

**Comment by Calvin-Huang** [comment]
I appreciate your recommendation. As you mentioned, Samsara do not have failed or retry method to make pubsub send the message again.

Here is the PR for it. #12  Check it out please.

**Comment by Aquamars** [comment]
Fantastic !
